image: php:latest

pipelines:
  default:
  - step:
      script:
      - echo "Pipeline Init"
      - apt-get update
      - apt-get -qq install git-ftp
      - echo "Initiating Push"
      - git ftp push -commit 1b9507926c639fec626fedfb7d825b156d8a3d0e -u $FTP_USERNAME -p $FTP_PASSWORD ftp://m15.coreserver.jp//public_html/xr-comparison.yutokun.com/
      - echo "Done Pushing"

