name: Deploy Website

on:
  push:
    branches: master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        server: ${{ secrets.ftp_server }}
        # FTP account username
        username: ${{ secrets.ftp_username }}
        # FTP account password
        password: ${{ secrets.ftp_password }}
        # The local folder to copy, defaults to root project folder
#         local-dir: # optional
        # Passes through options into git-ftp
#         git-ftp-args: # optional
        exclude: .github/**/*
          - .gitattributes
          - .gitignore
          - .jshintrc
          - *.md
          - *.afdesign
          - tsconfig.json

    - name: get commit message
      run: |
         echo "commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
    - name: show commit message
      run : echo $commitmsg

    - name: Tweet
      uses: ethomson/send-tweet-action@v1
      with:
        status: "@yutoVR 比較表がデプロイされました。変更内容: ${{ env.commitmsg }} https://xr-comparison.yutokun.com/"
        consumer-key: ${{ secrets.TWITTER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
