name: Deploy Website

on:
  push:
    branches: master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: FTP Deploy Release
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        server-dir: ${{ secrets.ftp_server_dir }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        exclude: .git/**/*
          - .github/**/*
          - .gitattributes
          - .gitignore
          - .jshintrc
          - *.md
          - *.afdesign
          - *.afphoto
          - tsconfig.json
          - src/**/*
          - svelte/**/*

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '17.4.0'

    - name: FTP Build with Svelte
      run: |
        cd ./svelte/
        npm install
        npm run build

    - name: FTP Deploy Svelte
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        server-dir: ${{ secrets.svelte_ftp_server_dir }}
        local-dir: ./svelte/public/
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        exclude: .git/**/*
          - .github/**/*
          - .gitattributes
          - .gitignore
          - .jshintrc
          - *.md
          - *.afdesign
          - *.afphoto
          - tsconfig.json
          - src/**/*

    - name: get commit message
      run: |
         echo "commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
    - name: show commit message
      run : echo $commitmsg

    - name: Tweet
      uses: ethomson/send-tweet-action@v1
      with:
        status: "@yutoVR 比較表がデプロイされました。変更内容: ${{ env.commitmsg }} https://xr-comparison.yutokun.com/"
        consumer-key: ${{ secrets.TWITTER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
